<?php
function chart_show_all(){
$room = "CTI";
$nodeMac = $_GET["ip"];
$nodeUrn = "urn:wisebed:ctitestbed:".$_GET['ip'];
$capability = array("Luminosity","Temperature");
$capabilityUrn =array("urn:wisebed:node:capability:light","urn:wisebed:node:capability:temperature");
$maxRows = 10;
$unit="(lux)";
$set_date= false;
?>
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/ jquery/1.7.0/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>
    <script type="text/javascript">
    <?php
        if (isset($_GET['from'])&&isset($_GET["to"]))
        {   $set_date=true;
            $from = explode("-",$_GET['from']);
            $to =explode("-",$_GET['to']);
            $date_from = mktime($from[3],$from[4],$from[5],$from[1],$from[2],$from[0])*1000;
            $date_to = mktime($to[3],$to[4],$to[5],$to[1],$to[2],$to[0])*1000;
        }

     ?>
  <? for ($i=0;$i<=1;$i++){ ?>
    var chart;



  $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container-<?= $nodeMac . '-' . $capability[$i] ?>',
                defaultSeriesType: 'spline',
                zoomType: 'x',
                spacingRight: 20
            },
            title: {
                text: '<?=$capability[$i]?> chart inside <?= $room?>'

            },
            subtitle: {
                text: '<?=$nodeMac?>'
            },
            xAxis: {
                type: 'datetime',
                dateTimeLabelFormats: {
                    day: '%e %b',
                    month: '%e %b'
                },
                tickPixelInterval: 400,
                maxZoom: 1000
            },
            yAxis: {
                title: {
                    text: '<?= $capability[$i]." ".$unit ?>'
                },
                min: 0.6,
                startOnTick: false,
                showFirstLabel: false
            },
            tooltip: {
                shared: true
            },
            legend: {
                enabled: false
            },
            plotOptions: {
                series: {
                    lineWidth: 1,
                    marker: {
                        enabled: false,
                        states: {
                            hover: {
                                enabled: true,
                                radius: 5
                            }
                        }
                    }
                }
            },
            series: [
                {
                    name: '<?= $capability[$i] ?> reading <?= $unit?>',
                    data: [
                        <?
                        if($set_date==1){
                            $tabdelimited = file_get_contents("http://uberdust.cti.gr/rest/testbed/1/node/".$nodeUrn."/capability/".$capabilityUrn[$i]."/tabdelimited/from/".$date_from."/to/".$date_to."/");
                        }else
                        {
                            $tabdelimited = file_get_contents("http://uberdust.cti.gr/rest/testbed/1/node/".$nodeUrn."/capability/".$capabilityUrn[$i]."/tabdelimited/limit/".$maxRows);
                        }
                        $lines = explode("\n", $tabdelimited);
                        unset($lines[count($lines)-1]);

                        $firstRow = explode("\t", $lines[0]);
                        print("         [".$firstRow[0]." , ".$firstRow[1]."]");
                        unset($lines[0]);

                        foreach ($lines as $thisLine) {
                          $row = explode("\t", $thisLine);

                          print(",\n                                 [".$row[0]." , ".$row[1]."]");
                        }
                        ?>
                    ]
                }
            ]
        });
    });
<?  } ?>
</script>
   <? for($i=0;$i<=1;$i++){ ?>
    <div id="container-<?= $nodeMac . '-' . $capability[$i] ?>" style="width: 100%; height: 400px"></div>

   <? }  
}//end of function

