<?php
function power_sensor_show_all(){
$room = "CTI Room 0.I.1";
$node1Mac = "150.140.5.67";
$node1Type = "iSense";
$nodeUrn1 = "urn:wisebed:ctitestbed:";
$capability1 = "Consumption";
$maxRows = 10;


?>
<?php 
	if(empty($_GET['ip'])){	
		$status_raw=file_get_contents("http://uberdust.cti.gr/rest/testbed/1/status/raw");
		$line = explode("\n", $status_raw);
		for($i=0; $i<sizeof($line); $i++){
			$nodetype= explode("\t", $line[$i]);		
			if(isset($nodetype[3])&& ($nodetype[3]=="powerstrip")){	
				$node=explode(":", $nodetype[0]);
				echo  '<p><a href="http://uberdust.cti.gr:81/uberdust/power?ip='.$node[3].'">'.$nodetype[0].'</a></p>';
			}	
		}			
	
	}
	else{ ?>
		<script>
		var values = new Array();
		var current = new Array();
		var max_value = new Array();
		var min_value = new Array();
		var minimum = 5000;
		var maximum = 0;      
		<?php
		$capabilities = file_get_contents("http://uberdust.cti.gr/rest/testbed/1/node/" . $nodeUrn1 . $_GET['ip'] . "/capabilities" );
		$line = explode("\n", $capabilities);
		$j=0;
		    $k=0;
		for($i=0; $i<sizeof($line); $i++){
			    if(substr($line[$i],-1,1)=="r"){
		         $k++;
		         $id = substr($line[$i],-2,1);
		         $latestreading= file_get_contents("http://uberdust.cti.gr/rest/testbed/1/node/" . $nodeUrn1 . $_GET['ip'] . "/capability/urn:wisebed:node:capability:" . $id . "r/latestreading");
		         $row = explode("\t", $latestreading);
		         $status[$k]=$row[1];
					
			    }
		
		    if(substr($line[$i],-1,1)=="s"){
		      $j++;?>
		        values[<?php echo $j;?>] = [<?php
		                $id = substr($line[$i],-2,1);
		                $tabdelimited = file_get_contents("http://uberdust.cti.gr/rest/testbed/1/node/". $nodeUrn1 . $_GET['ip'] . "/capability/urn:wisebed:node:capability:" . $id . "s/tabdelimited/limit/" . $maxRows);
		                $lines = explode("\n", $tabdelimited, $maxRows);
		                unset($lines[count($lines) - 1]);
		                $firstRow = explode("\t", $lines[0]);
		                print( $firstRow[1] );
		                unset($lines[0]);
		                foreach ($lines as $thisLine) {
		                    $row = explode("\t", $thisLine);
		                    print(",".$row[1]);
		                }
		            ?>];
	

		      <?php echo "current[$j] = $firstRow[1];";?>
		      <?php echo "max_value[$j] = Math.max.apply(Math, values[$j]);"; ?>
		      <?php echo "min_value[$j] = Math.min.apply(Math, values[$j]);";?>
			  <?php echo "if(min_value[".$j."]< minimum){ mimimum = min_value[".$j."];} "; ?>
		      if(max_value[<?php echo $j;?>]> maximum){ maximum = max_value[<?php echo $j; ?>];}
		     if(min_value[<?php echo $j;?>]< minimum){ minimum = min_value[<?php echo $j; ?>];}
	
		    <?php

		    }	
		}
	
		 $count=$j;
		for($j=1; $j<=$count; $j++){	
		?>
	
		
		$(function drawChart(){
	
		    var chart;
		    chart = new Highcharts.Chart({
		        chart: {
		            renderTo: 'chart_div<?php echo $j;?>',
		            type: 'gauge',
		            plotBackgroundColor: '#222222',
		            plotBackgroundImage: null,
		            plotBorderWidth: 0,
		            plotShadow: false
		        },
		        title: {
		            text: 'Sensor <?php echo $j;?>'
		        },
		        pane: {
		            startAngle: -150,
		            endAngle: 150,
		            background: [
		                {
		                    backgroundColor: {
		                        linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
		                        stops: [
		                            [0, '#FFF'],
		                            [1, '#333']
		                        ]
		                    },
		                    borderWidth: 0,
		                    outerRadius: '109%'
		                },
		                {
		                    backgroundColor: {
		                        linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
		                        stops: [
		                            [0, '#333'],
		                            [1, '#FFF']
		                        ]
		                    },
		                    borderWidth: 1,
		                    outerRadius: '107%'
		                },
		                {
		                    // default background
		                },
		                {
		                    backgroundColor: '#DDD',
		                    borderWidth: 0,
		                    outerRadius: '105%',
		                    innerRadius: '103%'
		                }
		            ]
		        },

		        // the value axis
		        yAxis: {
		            min: minimum,
		            max: maximum,

		                minorTickInterval: 'auto',
		                minorTickWidth: 1,
		                minorTickLength: 10,
		                minorTickPosition: 'inside',
		                minorTickColor: '#666',

		                tickPixelInterval: 30,
		                tickWidth: 2,
		                tickPosition: 'inside',
		                tickLength: 10,
		                tickColor: '#666',
		                labels: {
		                    step: 2,
		                    rotation: 'auto'
		                    },
		                title: {
		                    text: 'mA'
		                    },
		                plotBands: [{
		                    from: 0,
		                    to: maximum*0.75,
		                    color: '#55BF3B' // green
		                    }, {
		                    from: maximum*0.75,
		                    to: maximum*0.875 ,
		                    color: '#DDDF0D' // yellow
		                    }, {
		                    from: maximum*0.875,
		                    to: maximum,
		                    color: '#DF5353' // red
		                    }]
		                },

		                series: [{
		                    name: 'Current Flow',
		                    data: [current[<?php echo $j;?>]],
		                    tooltip: {
		                    valueSuffix: ' mA'
		                    }
		                }]
		       });
		chart.setSize(230, 230, false);
		});	//end of function drawchart




		<?php
		
		}//end of for loop
		?>
	    </script>

	    <?php
		echo "<table>";
       		 for ($i = 1; $i <= $count; $i++) {
		 echo "<tr>";
		 echo "<td><ul style='list-style: none;'>";
			 if($status[$i]==0.0)
			    echo "<li><img src='/uberdust/sites/all/images/sensors/led-off-md.png' alt='off' width='65' height='65'></li>";
			 elseif($status[$i]==1.0)
			     echo "<li><img src='/uberdust/sites/all/images/sensors/led-on-md.png' alt='on' width='65' height='65'></li>";
			 if($status[$i]==0.0)
		    	     echo "<li><img src='/uberdust/sites/all/images/sensors/newswitch0.png' alt='off' width='80' height='80'></li>";
		    	 elseif($status[$i]==1.0)
		       	     echo "<li><img src='/uberdust/sites/all/images/sensors/newswitch1.png' alt='off' width='80' height='80'></li>";
		 echo "</ul></td>";
		 echo "<td><div id='chart_div" . $i . "' style='width: 400px; height: 300px; margin: 0 auto' ></div></td>";
		 echo "</tr>";
        }//for
	echo "</table>";
   }//if(empty($_GET)) 
}//function


