<?php
function power_sensor_show_all($show_controls,$testbed){
    $nodeUrn1 = "";
    $maxRows = 10;
    ?>


    <?php
	if(empty($_GET['ip'])){
		$status_raw=file_get_contents("http://uberdust.cti.gr/rest/testbed/".$testbed."/status/raw");
		$line = explode("\n", $status_raw);
        echo ' <p>Choose one of the available power strips:</p> ';
		for($i=0; $i<sizeof($line); $i++){
			$nodetype= explode("\t", $line[$i]);
			if(isset($nodetype[3])&& (($nodetype[3]=="powerstrip")||($nodetype[3]=="powersensor"))){
				$node = explode(":", $nodetype[0]);
				$count = sizeof($node)-1;
				echo  '<p><a href="http://uberdust.cti.gr:81/uberdust/power?ip='.$node[$count].'">'.$nodetype[0].'</a></p>';
			}
		}
		for ($i=0; $i<$count; $i++)
		{
			$nodeUrn1 = $nodeUrn1.$node[$i].":";
		}

	}
	else{ ?>
    <script>
    window.values = new Array();
    window.current = new Array();
    window.state=new Array();
    var max_value = new Array();
    var min_value = new Array();
    var minimum = 5000;
    var maximum = 0;



    <?php
         $status_raw=file_get_contents("http://uberdust.cti.gr/rest/testbed/".$testbed."/status/raw");
		$line = explode("\n", $status_raw);
		for($i=0; $i<sizeof($line); $i++){
			$nodetype= explode("\t", $line[$i]);
			if(isset($nodetype[3])&& (($nodetype[3]=="powerstrip")||($nodetype[3]=="powersensor"))){
				$node = explode(":", $nodetype[0]);
				$count = sizeof($node)-1;
				break;
			}
		}
		for ($i=0; $i<$count; $i++)
		{
			$nodeUrn1 = $nodeUrn1.$node[$i].":";
		}


        $capabilities = file_get_contents("http://uberdust.cti.gr/rest/testbed/" . $testbed . "/node/" . $nodeUrn1 . $_GET['ip'] . "/capabilities" );
        $line = explode("\n", $capabilities);
        $j=0;
        $k=0;
        $c=0;
        for($i=0; $i<sizeof($line); $i++){
        if(substr($line[$i],-1,1)=="i"){
                 $c++;
                 $id = substr($line[$i],-2,1);
                 $latestreading= file_get_contents("http://uberdust.cti.gr/rest/testbed/" . $testbed . "/node/" . $nodeUrn1 . $_GET['ip'] . "/capability/urn:wisebed:node:capability:" . $id . "r/latestreading");
                 $row = explode("\t", $latestreading);
                 $indicator[$c]=$row[1];

            }
        if(substr($line[$i],-1,1)=="r"){
                 $k++;
                 $id = substr($line[$i],-2,1);
                 $latestreading= file_get_contents("http://uberdust.cti.gr/rest/testbed/".$testbed."/node/" . $nodeUrn1 . $_GET['ip'] . "/capability/urn:wisebed:node:capability:" . $id . "r/latestreading");
                 $row = explode("\t", $latestreading);
                 $status[$k]=$row[1];

            }

            if(substr($line[$i],-1,1)=="s"){
              $j++;?>
            //////////////////////////////
    values[<?php echo $j;?>] = [<?php
                        $id = substr($line[$i],-2,1);
                        $tabdelimited = file_get_contents("http://uberdust.cti.gr/rest/testbed/".$testbed."/node/". $nodeUrn1 . $_GET['ip'] . "/capability/urn:wisebed:node:capability:" . $id . "s/latestreading");///tabdelimited/limit/maxrows
                        $lines = explode("\n", $tabdelimited, $maxRows);
                        unset($lines[count($lines) - 1]);
                        $firstRow = explode("\t", $lines[0]);
                        print( $firstRow[1] );
                        unset($lines[0]);
                        foreach ($lines as $thisLine) {
                            $row = explode("\t", $thisLine);
                            print(",".$row[1]);
                        }
                    ?>];


    <?php echo "current[$j] = $firstRow[1];";
        $current[$j]=$firstRow[1];?>
    <?php

        }//end if	==s
}// end of for loop
?>
    <?php
     $count=$j;
    for($j=1; $j<=$count; $j++){
    $nodetab =file_get_contents("http://uberdust.cti.gr/rest/testbed/".$testbed."/node/" . $nodeUrn1 . $_GET['ip'] . "/capability/nodetype/tabdelimited/limit/10");
    $nodetype= explode("\t", $nodetab);
    if(isset($nodetype[1])&&($nodetype[1]=="powerstrip")){$max=1500;$red=1200; $yellow=800; }
    else{$max=20000; $red=16000; $yellow=12000;}
    unset($nodetype);
    ?>


    $(function drawChart(){

        var chart<?php echo $j;?>;
        chart<?php echo $j;?> = new Highcharts.Chart({

                chart: {
                    renderTo: 'chart_div<?php echo $j;?>',
                    type: 'gauge',
                    plotBackgroundColor: '#222222',
                    plotBackgroundImage: null,
                    plotBorderWidth: 0,
                    plotShadow: false

                },

                title: {
                    text: 'Sensor <?php echo $j;?>'
                },

                pane: {
                    startAngle: -150,
                    endAngle: 150,
                    background: [
                        {
                            backgroundColor: {
                                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                                stops: [
                                    [0, '#FFF'],
                                    [1, '#333']
                                ]
                            },
                            borderWidth: 0,
                            outerRadius: '109%'
                        },
                        {
                            backgroundColor: {
                                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                                stops: [
                                    [0, '#333'],
                                    [1, '#FFF']
                                ]
                            },
                            borderWidth: 1,
                            outerRadius: '107%'
                        },
                        {
                            // default background
                        },
                        {
                            backgroundColor: '#FFF',
                            borderWidth: 0,
                            outerRadius: '105%',
                            innerRadius: '103%'
                        }
                    ]
                },

                // the value axis
                yAxis: {
                    min: 0,
                    max: <?php echo $max;?>,
                    minorTickInterval: 'auto',
                    minorTickWidth: 1,
                    minorTickLength: 10,
                    minorTickPosition: 'inside',
                    minorTickColor: '#666',

                    tickPixelInterval: 30,
                    tickWidth: 2,
                    tickPosition: 'inside',
                    tickLength: 10,
                    tickColor: '#666',
                    labels: {
                        step: 2,
                        rotation: 'auto'
                    },
                    title: {
                        text: 'mA'
                    },
                    plotBands: [{
                        from: 0,
                        to: 70,
                        color: '#A9A9A9	' // grey
                    },{
                        from: 70,
                        to: <?php echo $yellow;?>,
                        color: '#55BF3B' // green
                    }, {
                        from: <?php echo $yellow;?>,
                        to: <?php echo $red;?>,
                        color: '#DDDF0D' // yellow
                    }, {
                        from: <?php echo $red;?>,
                        to: <?php echo $max;?>,
                        color: '#DF5353' // red
                    }]
                },

                series: [{
                    name: 'Current Flow',
                    data: [window.current[<?php echo $j;?>]],
                    tooltip: {
                        valueSuffix: ' mA'
                    }
                }]
            },
            // Add some life
            function (chart<?php echo $j;?>){
                if (!chart<?php echo $j;?>.renderer.forExport) {
                    setInterval(function () {
                        var point<?php echo $j;?> = chart<?php echo $j;?>.series[0].points[0],
                            newVal<?php echo $j;?>,
                        // inc = Math.round((Math.random() - 0.5) * 20);

                            newVal<?php echo $j;?> = window.current[<?php echo $j; ?>];
                        point<?php echo $j;?>.update(parseFloat(newVal<?php echo $j;?>));
                    }, 3000);
                }
            });

        chart<?php echo $j;?>.setSize(230, 230, false);

    });


    <?php

    } // end for loop (drawchart)

for($j=1;$j<=$count;$j++){
    ?>
            connect("uberdust.cti.gr", "<?php echo $nodeUrn1.$_GET['ip'];?>" , "urn:wisebed:node:capability:<?php echo $j;?>s",function(value2add){
                var val= new Array();
                var capability=" ";
                val=value2add.split(" ");
                capability=val[1].split(":");
                id=capability[4].split("");
                window.current[id[0]]=val[8];
            });
        <?
        if(isset($indicator[$j])){ ?>
            connect("uberdust.cti.gr","<?php echo $nodeUrn1.$_GET['ip'];?>" ,"urn:wisebed:node:capability:<?php echo $j;?>i",function(value2add){
                var val= new Array();
                var capability=" ";
                val=value2add.split(" ");
                capability=val[1].split(":");
                id=capability[4].split("");
                if(val[8]==1.0){
                     document.getElementById("led"+id[0]).src="/uberdust/sites/all/images/sensors/led-on-md.png";
                }else{
                     document.getElementById("led"+id[0]).src="/uberdust/sites/all/images/sensors/led-off-md.png";
                }
            });
  <?php }
       if(isset($status[$j])){ ?>
            connect("uberdust.cti.gr","<?php echo $nodeUrn1.$_GET['ip'];?>","urn:wisebed:node:capability:<?php echo $j?>r",function(value2add){
                var val= new Array();
                var capability=" ";
                val=value2add.split(" ");
                capability=val[1].split(":");
                id=capability[4].split("");
                if(val[8]==1.0){
                    document.getElementById("myswitch"+id[0]).src="/uberdust/sites/all/images/sensors/newswitch1.png";
                }else{
                    document.getElementById("myswitch"+id[0]).src="/uberdust/sites/all/images/sensors/newswitch0.png";
                }
            });
        <?php

        }
    }
      ?>
    //





    //switch onclick
		function activate(zone,status,testbed,nodeUrn,node){
			if (status==1.0){
				window.state[zone]=0.0;
				document.getElementById('myswitch'+zone+'').src="/uberdust/sites/all/images/sensors/newswitch0.png";
                $.post( "http://uberdust.cti.gr/rest/testbed/"+testbed+"/node/"+nodeUrn+node+"/capability/urn:wisebed:node:capability:" +zone +"r/0/",0);
			}
			else{
				window.state[zone]=1.0;
				document.getElementById('myswitch'+zone+'').src="/uberdust/sites/all/images/sensors/newswitch1.png";
                $.post( "http://uberdust.cti.gr/rest/testbed/"+testbed+"/node/"+nodeUrn+node+"/capability/urn:wisebed:node:capability:" +zone +"r/1/",1);
			}
		}
 </script>

	   <?php
                echo "<table aling='center'>";
                 for ($i = 1; $i <= $count; $i++) {
                 echo "<tr>";
                         echo "<td style='vertical-align:top;'>";
                        echo "<table style='vertical-align:top;'>";
                         echo "<tr><td>";
                                if($show_controls==1){
                                     if(isset($status[$i])&& $status[$i]==0.0)
                                            echo " <img src='/uberdust/sites/all/images/sensors/newswitch0.png' onclick = 'activate(".$i.",window.state[".$i."],".$testbed.",".$nodeUrn1.",".$_GET['ip'].")' id= 'myswitch".$i."' alt='switch' height='80' width='80'/>";
                                     elseif(isset($status[$i])&& $status[$i]==1.0)
                                            echo " <img src='/uberdust/sites/all/images/sensors/newswitch1.png' onclick = 'activate(".$i.",window.state[".$i."],".$testbed.",".$nodeUrn1.",".$_GET['ip'].")' id= 'myswitch".$i."' alt='switch' height='80' width='80'/>";
                                }
                        echo "</td></tr>";
                        echo "<tr><td>";
                                 if(isset($indicator[$i])&& $indicator[$i]==0.0)
                                     echo "<img id='led".$i."' src='/uberdust/sites/all/images/sensors/led-off-md.png' alt='off' width='65' height='65'>";
                                 elseif(isset($indicator[$i])&& $indicator[$i]==1.0)
                                     echo "<img id='led".$i."' src='/uberdust/sites/all/images/sensors/led-on-md.png' alt='on' width='65' height='65'>";
                        echo "</td></tr>";
                        echo "</table>";
                        echo "</td>";
                         echo "<td id='chart_div" . $i . "' style='width: 400px; margin: 0 0 0 0; ' ></td>";
                 echo "</tr>";
        }//for

	echo "</table>";
   }//if(empty($_GET)) 
}//function


