<?php
function display_temperature($testbed,$node,$capability,$div){
    $node_prefix="";
    $cap_prefix="";
    $temp_node  =explode(":",$node);
    $temp_capability = explode(":",$capability);
    for($i=0;$i<count($temp_node)-1;$i++){
        $node_prefix=$node_prefix.$temp_node[$i].":";
    }
    for($i=0;$i<count($temp_capability)-1;$i++){
        $cap_prefix=$cap_prefix.$temp_capability[$i].":";
    }
    $node = $temp_node[count($temp_node)-1];
    $capability = $temp_capability[count($temp_capability)-1];
    ?>

<script type="text/javascript" src="/uberdust/misc/js/excanvas.js"></script>
<![endif]-->
<script type="text/javascript" src="/uberdust/misc/js/segment-display.js"></script>
<script type="text/javascript">

    var display = new SegmentDisplay("<? echo $div;?>");
    display.pattern         = "##.##";
    display.displayAngle    = 10;
    display.digitHeight     = 20;
    display.digitWidth      = 12;
    display.digitDistance   = 2.5;
    display.segmentWidth    = 2.5;
    display.segmentDistance = 0.5;
    display.segmentCount    = 7;
    display.cornerType      = 3;
    display.colorOn         = "#9F000F";
    display.colorOff        = "#221";
    display.draw();
    data= <?php
                $latestreading = file_get_contents("http://uberdust.cti.gr/rest/testbed/$testbed/node/".$node_prefix.$node."/capability/".$cap_prefix.$capability."/latestreading");
                $row = explode("\t", $latestreading);
                echo $row[1];
                 ?>;
    value = data.split(".");
//    display.setValue(value[0]+"."+value[1]);
    display.setValue(data);
    connect("uberdust.cti.gr", "<?php echo $node_prefix.$node;?>" , "<?php echo $cap_prefix.$capability;?>",function(value2add){
        var val=value2add.split(" ");
        var value =val[8].split("."));
//        display.setValue(value[0]+"."+value[1]);
        display.setValue(val[8]);

    });

</script>
<?php
}